locastic_sylius_translations_admin_paths:
    prefix: "/%sylius_admin.path_name%/translations"
    resource: 'routes/translations.yaml'

locastic_sylius_translations_admin_clear_cache:
    path: "/%sylius_admin.path_name%/clear-cache"
    methods: [ GET ]
    controller: Locastic\SyliusTranslationPlugin\Controller\Admin\ClearCacheAction
