imports:
    - { resource: '@LocasticSyliusTranslationPlugin/config/routes.yaml' }
    - { resource: '@LocasticSyliusTranslationPlugin/config/routes.yaml' }
    - { resource: '@LocasticSyliusTranslationPlugin/config/services.yaml' }
